#!/bin/bash

# save for current project
git config credential.helper store

# remove from current project 
git config --unset credential.helper

# save global to ur %HOME% directory
git config --global credential.helper store
